<?php

$params = array_merge(
        require(__DIR__ . '/../../common/config/params.php'), require(__DIR__ . '/../../common/config/params-local.php'), require(__DIR__ . '/params.php'), require(__DIR__ . '/params-local.php')
);

return [
    'timezone' => 'Asia/Kolkata',
    'id' => 'app-IRISORG',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'IRISORG\controllers',
    'modules' => [
        'v1' => [
            'basePath' => '@app/modules/v1',
            'class' => 'IRISORG\modules\v1\Module',
        ],
    ],
    'components' => [
//        'schedule' => 'omnilight\scheduling\Schedule',
        'hepler' => [
            'class' => 'common\components\HelperComponent',
        ],
        'user' => [
            'identityClass' => 'common\models\CoLogin',
            'enableSession' => false,
            'loginUrl' => null,
        ],
        'request' => [
            'class' => '\yii\web\Request',
            'enableCookieValidation' => false,
            'enableCsrfValidation' => false,
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/user'], 'extraPatterns' => ['POST login' => 'login', 'POST createuser' => 'createuser', 'POST updateuser' => 'updateuser', 'GET getuser' => 'getuser', 'GET getlogin' => 'getlogin', 'POST updatelogin' => 'updatelogin', 'GET getuserslistbyuser' => 'getuserslistbyuser', 'POST assignroles' => 'assignroles', 'GET getusercredentialsbytoken' => 'getusercredentialsbytoken', 'POST logout' => 'logout', 'POST passwordauth' => 'passwordauth', 'POST changepassword' => 'changepassword']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/role'], 'extraPatterns' => ['POST createrole' => 'createrole', 'POST updaterole' => 'updaterole', 'GET getrole' => 'getrole', 'GET getactiverolesbyuser' => 'getactiverolesbyuser', 'GET getmyroles' => 'getmyroles']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/organization'], 'extraPatterns' => ['GET getorg' => 'getorg', 'GET getorgmodules' => 'getorgmodules', 'POST updaterolerights' => 'updaterolerights', 'POST getorgmodulesbyrole' => 'getorgmodulesbyrole', 'POST updatesharing' => 'updatesharing', 'GET getshareorglist' => 'getshareorglist', 'GET getpatientshareresources' => 'getpatientshareresources', 'POST updatepatientsharing' => 'updatepatientsharing', 'GET getpatientsharetenants' => 'getpatientsharetenants', 'GET getorgbranches' => 'getorgbranches']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roommaintenance'], 'extraPatterns' => ['GET getmaintenancelist' => 'getmaintenancelist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/floor'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/ward'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getwardlist' => 'getwardlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roomchargecategory'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getroomchargecategorylist' => 'getroomchargecategorylist', 'GET getchargelist' => 'getchargelist', 'GET getroomchargelist' => 'getroomchargelist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roomchargesubcategory'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getroomchargesubcategorylist' => 'getroomchargesubcategorylist', 'POST saveallsubcategory' => 'saveallsubcategory', 'POST deleteallsubcategory' => 'deleteallsubcategory']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roomchargeitem'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getroomchargeitemlist' => 'getroomchargeitemlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roomtype'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getroomtypelist' => 'getroomtypelist', 'GET getroomtypesroomslist' => 'getroomtypesroomslist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/room'], 'extraPatterns' => ['GET getrooms' => 'getrooms', 'GET getroomandroomtypes' => 'getroomandroomtypes', 'POST assignroomtypes' => 'assignroomtypes', 'GET getroomlist' => 'getroomlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/roomcharge'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getroomchargecategorylist' => 'getroomchargecategorylist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/speciality'], 'extraPatterns' => ['GET getspecialitylist' => 'getspecialitylist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientcategory'], 'extraPatterns' => ['GET getpatientcategorylist' => 'getpatientcategorylist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientgroup'], 'extraPatterns' => ['GET getpatientgrouplist' => 'getpatientgrouplist', 'GET getpatientgroupbypatient' => 'getpatientgroupbypatient', 'POST syncpatient' => 'syncpatient']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/chargepercategory']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/chargepersubcategory'], 'extraPatterns' => ['GET getroomchargesubcategorylist' => 'getroomchargesubcategorylist', 'POST saveallchargecategory' => 'saveallchargecategory']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/internalcode'], 'extraPatterns' => ['GET getinternalcode' => 'getinternalcode']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/doctorschedule'], 'extraPatterns' => ['POST remove' => 'remove', 'POST removeall' => 'removeall', 'POST createschedule' => 'createschedule']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/country'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/state'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/city'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/alert'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getalertlist' => 'getalertlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patient'], 'extraPatterns' => ['POST remove' => 'remove', 'POST registration' => 'registration', 'GET getpatientaddress' => 'getpatientaddress', 'GET getpatientlist' => 'getpatientlist', 'POST getpatientbyguid' => 'getpatientbyguid', 'POST getagefromdate' => 'getagefromdate', 'POST getpatienttimeline' => 'getpatienttimeline', 'GET getpatientroutelist' => 'getpatientroutelist', 'GET getpatientfrequencylist' => 'getpatientfrequencylist', 'POST uploadimage' => 'uploadimage', 'POST importpatient' => 'importpatient', 'POST getpatient' => 'getpatient', 'POST mergepatients' => 'mergepatients']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/encounter'], 'extraPatterns' => ['POST remove' => 'remove', 'POST createappointment' => 'createappointment', 'POST createadmission' => 'createadmission', 'GET getencounters' => 'getencounters', 'GET inpatients' => 'inpatients', 'GET outpatients' => 'outpatients', 'GET getencounterlistbypatient' => 'getencounterlistbypatient', 'POST patienthaveactiveencounter' => 'patienthaveactiveencounter', 'POST appointmentseenencounter' => 'appointmentseenencounter', 'POST patienthaveunfinalizedencounter' => 'patienthaveunfinalizedencounter', 'GET getroomchargehistory' => 'getroomchargehistory', 'POST updaterecurringroomcharge' => 'updaterecurringroomcharge', 'POST cancelrecurringroomcharge' => 'cancelrecurringroomcharge', 'POST savebillnote' => 'savebillnote', 'GET getallbilling' => 'getallbilling']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/procedure'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getprocedurebyencounter' => 'getprocedurebyencounter', 'GET getconsultantsbyprocedure' => 'getconsultantsbyprocedure', 'POST bulkinsert' => 'bulkinsert']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/admission'], 'extraPatterns' => ['POST remove' => 'remove', 'POST patientswap' => 'patientswap', 'POST canceladmission' => 'canceladmission', 'POST updateadmission' => 'updateadmission']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/appointment'], 'extraPatterns' => ['POST changestatus' => 'changestatus', 'POST remove' => 'remove', 'GET getfutureappointments' => 'getfutureappointments', 'GET getfutureappointmentslist' => 'getfutureappointmentslist', 'POST bulkcancel' => 'bulkcancel', 'POST bulkreschedule' => 'bulkreschedule']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientalert'], 'extraPatterns' => ['GET getpatientalerts' => 'getpatientalerts', 'POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientconsultant'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getpatconsultantsbyencounter' => 'getpatconsultantsbyencounter', 'POST bulkinsert' => 'bulkinsert']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientnotes'], 'extraPatterns' => ['GET getpatientnotes' => 'getpatientnotes', 'POST remove' => 'remove', 'POST assignnotes' => 'assignnotes', 'POST seennotes' => 'seennotes']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacybrand'], 'extraPatterns' => ['POST remove' => 'remove', 'POST getbrands' => 'getbrands']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacybrandrep'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getallbrands' => 'getallbrands', 'GET getalldivisions' => 'getalldivisions']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacybranddivision'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacydrugclass'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getdruglist' => 'getdruglist', 'GET getdrugbygeneric' => 'getdrugbygeneric']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/genericname'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getgenericlist' => 'getgenericlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyprodesc'], 'extraPatterns' => ['POST remove' => 'remove', 'POST adddescriptionroutes' => 'adddescriptionroutes']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacypacking'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getpackinglist' => 'getpackinglist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacysupplier'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getsupplierlist' => 'getsupplierlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyvat'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getvatlist' => 'getvatlist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacydruggeneric'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savedruggeneric' => 'savedruggeneric', 'POST updatedruggeneric' => 'updatedruggeneric']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientcasesheet'], 'extraPatterns' => ['POST createcasesheet' => 'createcasesheet']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyproduct'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getproductlist' => 'getproductlist', 'GET getproductdescriptionlist' => 'getproductdescriptionlist', 'GET getproductlistbyname' => 'getproductlistbyname', 'POST searchbycriteria' => 'searchbycriteria', 'POST adjuststock' => 'adjuststock', 'POST updatebatch' => 'updatebatch', 'GET getdrugclasslistbyname' => 'getdrugclasslistbyname', 'GET getgenericlistbydrugclass' => 'getgenericlistbydrugclass', 'GET getproductlistbygeneric' => 'getproductlistbygeneric', 'POST getprescription' => 'getprescription', 'POST getproducts' => 'getproducts', 'GET getdrugproductbygeneric' => 'getdrugproductbygeneric', 'POST getbatchdetails' => 'getbatchdetails']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacypurchase'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savepurchase' => 'savepurchase', 'GET reportlist' => 'reportlist', 'GET getpurchases' => 'getpurchases', 'GET getpurchase' => 'getpurchase', 'GET getpurchasebillno' => 'getpurchasebillno']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyproductbatch'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getbatchbyproduct' => 'getbatchbyproduct']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacysale'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savesale' => 'savesale', 'GET getsales' => 'getsales', 'GET getsalebillno' => 'getsalebillno']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacypurchasereturn'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savepurchasereturn' => 'savepurchasereturn']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacysalereturn'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savesalereturn' => 'savesalereturn']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyreport'], 'extraPatterns' => ['POST purchasereport' => 'purchasereport', 'POST salereport' => 'salereport', 'POST salereturnreport' => 'salereturnreport', 'POST prescriptionregisterreport' => 'prescriptionregisterreport', 'POST stockreport' => 'stockreport', 'GET getsalegrouplist' => 'getsalegrouplist']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacysalebilling'], 'extraPatterns' => ['POST makepayment' => 'makepayment']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientbillingpayment'], 'extraPatterns' => ['POST remove' => 'remove', 'GET billinghistory' => 'billinghistory']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientbillingothercharge'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientbillingextraconcession'], 'extraPatterns' => ['POST remove' => 'remove', 'POST addcharge' => 'addcharge']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientprescription'], 'extraPatterns' => ['POST remove' => 'remove', 'POST saveprescription' => 'saveprescription', 'GET getactiveroutes' => 'getactiveroutes', 'GET getdescriptionroutes' => 'getdescriptionroutes']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientvitals'], 'extraPatterns' => ['POST remove' => 'remove', 'GET getpatientvitals' => 'getpatientvitals', 'POST assignvitals' => 'assignvitals', 'POST seenvitals' => 'seenvitals']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientprescriptionfavourite'], 'extraPatterns' => ['GET getpatientprescriptionfavourite' => 'getpatientprescriptionfavourite', 'POST togglefavourite' => 'togglefavourite']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/appconfiguration'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientdocuments'], 'extraPatterns' => ['GET getpatientdocuments' => 'getpatientdocuments', 'GET getdocumenttype' => 'getdocumenttype', 'GET getdocument' => 'getdocument', 'POST savedocument' => 'savedocument', 'POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyreorderhistory'], 'extraPatterns' => ['POST remove' => 'remove', 'POST savepurchase' => 'savepurchase', 'GET reportlist' => 'reportlist', 'GET getpurchases' => 'getpurchases', 'POST reorder' => 'reorder', 'POST addreorderhistory' => 'addreorderhistory', 'POST removeitem' => 'removeitem']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientscanneddocuments'], 'extraPatterns' => ['GET getscanneddocuments' => 'getscanneddocuments', 'POST savedocument' => 'savedocument', 'POST remove' => 'remove', 'GET getscanneddocument' => 'getscanneddocument']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyroute'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientotherdocuments'], 'extraPatterns' => ['POST remove' => 'remove']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/myworkreports'], 'extraPatterns' => ['POST opdoctorpaymentreport' => 'opdoctorpaymentreport', 'POST ipbillstatus' => 'ipbillstatus', 'POST dischargedpatientbills' => 'dischargedpatientbills', 'POST ipdoctorspay' => 'ipdoctorspay']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacypurchasebilling'], 'extraPatterns' => ['POST makepayment' => 'makepayment']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/doctorinterval'], 'extraPatterns' => ['POST setintervaltime' => 'setintervaltime']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/hsn']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/auditlog']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientallergies']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacygst']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/pharmacyproductunit']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientresults']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/patientrefundpayment']],
                ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/orgsetting']],
            ],
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'v1/default/error',
        ],
    ],
    'params' => $params,
];
